version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run: cd ./client-web-ui && yarn install --ignore-engines && npm run build
      - sonarcloud/scan

  test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: cd ./client-web-ui && npm run test

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3
    
workflows:
  build_test_deploy:
    jobs:
      - build:
        context: SonarCloud
      - test:
          requires:
            - build