version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/node:19.0.0'
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: 'cd ./client-web-ui && yarn install --ignore-engines && npm run build'
      - sonarcloud/scan

  test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: cd ./client-web-ui && yarn install --ignore-engines && npm run build
      - run: cd ./client-web-ui && npm run test

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  main:
    jobs:
      - build:
        context: SonarCloud