version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3
  sonarcloud: sonarsource/sonarcloud@1.0.3

jobs:
  build:
    docker:
      - image: 'cimg/node:19.0.0'
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: 'cd ./client-web-ui && yarn install --ignore-engines && npm run build'
      - sonarcloud/scan
      
  test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: cd ./client-web-ui && yarn install --ignore-engines && npm run build
      - run: cd ./client-web-ui && npm run test

workflows:
  main:
    jobs:
      #- test
      #- build:
      #    context: SonarCloud
      #    requires:
      #      - test
      - aws-ecr/build-and-push-image:
          path: ./client-web-ui/
          region: ${AWS_REGION}
          repo: ${CIRCLE_PROJECT_REPONAME}
          tag: latest
          #requires:
          #  - test
          filters:
            branches:
              only:
                - main
                - develop
