version: 2.1

jobs:
  build:
    machine:
      - image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: 'cd ./client-web-ui && yarn install --ignore-engines && npm run build'
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud