version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/node:19.0.0'
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: 'cd ./client-web-ui && yarn install --ignore-engines && npm run build'
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  build_and_test:
    jobs:
      - build:
        context: SonarCloud