export const data = [
    {
        id: 1,
        image: "cameras/image.jpg",
        camera: 1,
        location: "Office 1",
        desc: "Lorem Ipsum",
    },
    {
        id: 2,
        image: "team/image2.jpg",
        camera: 2,
        location: "House 99",
        desc: "Lorem Ipsum",
    },
    {
        id: 3,
        image: "cameras/image2.jpg",
        camera: 3,
        location: "Office 2",
        desc: "Lorem Ipsum",
    },
    {
        id: 4,
        image: "cameras/image.jpg",
        camera: 4,
        location: "Office 3",
        desc: "Lorem Ipsum",
    },
    {
        id: 5,
        image: "cameras/image.jpg",
        camera: 5,
        location: "Office 4",
        desc: "Lorem Ipsum",
    },
    {
        id: 6,
        image: "cameras/image2.jpg",
        camera: 6,
        location: "Office 5",
        desc: "Lorem Ipsum",
    },
    {
        id: 7,
        image: "cameras/image2.jpg",
        camera: 7,
        location: "Office 6",
        desc: "Lorem Ipsum",
    },
    {
        id: 8,
        image: "cameras/image2.jpg",
        camera: 8,
        location: "Office 7",
        desc: "Lorem Ipsum",
    },
    {
        id: 9,
        image: "cameras/image.jpg",
        camera: 9,
        location: "House 34",
        desc: "Lorem Ipsum",
    },
    {
        id: 10,
        image: "cameras/image.jpg",
        camera: 10,
        location: "House 8",
        desc: "Lorem Ipsum",
    },    {
        id: 11,
        image: "cameras/image2.jpg",
        camera: 11,
        location: "Airport 10",
        desc: "Lorem Ipsum",
    }
];